version: "2"

services:
  zk:
    image: bobrik/zookeeper
    network_mode: bridge
    ports:
      - 2181:2181
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1

  master:
    image: mesosphere/mesos-master:1.2.0
    restart: always
    network_mode: bridge
    ports:
      - 5050:5050
    links:
      - zk
    environment:
      MESOS_ZK: zk://zk:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_REGISTRY: replicated_log # default is in_memory for some reason
      MESOS_HOSTNAME: master
    depends_on:
      - zk

  slave-one:
    image: mesosphere/mesos-slave:1.2.0
    restart: always
    network_mode: bridge
    ports:
      - 5051:5051
    pid: host
    links:
      - zk
      - master
    environment:
      MESOS_MASTER: zk://zk:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 505
      MESOS_RESOURCES: ports(*):[10000-11999]
      MESOS_WORK_DIR: /tmp/mesos
      MESOS_HOSTNAME: mesos-slave.dc1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk

  slave-two:
      image: mesosphere/mesos-slave:1.2.0
      restart: always
      network_mode: bridge
      ports:
        - 5052:5052
      pid: host
      links:
        - zk
        - master
      environment:
        MESOS_MASTER: zk://zk:2181/mesos
        MESOS_CONTAINERIZERS: docker,mesos
        MESOS_PORT: 5052
        MESOS_RESOURCES: ports(*):[10000-11999]
        MESOS_WORK_DIR: /tmp/mesos
        MESOS_HOSTNAME: mesos-slave.dc2
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zk

  marathon:
    image: mesosphere/marathon:v1.3.6
    restart: always
    network_mode: bridge
    links:
      - zk
      - slave-one
    ports:
      - 8080:8080
    environment:
      MARATHON_MASTER: zk://zk:2181/mesos
      MARATHON_ZK: zk://zk:2181/mesos
    depends_on:
      - zk